version: "3.5"
services:
  server:
    container_name: mern-server
    build: ./server/
    restart: always
    ports:
      - "8081:8000"
    volumes:
      - ./server/:/usr/src/app/
  client:
    container_name: mern-client
    build: ./client/
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./client/dist/:/usr/share/nginx/html/
