version: "3.5"
services:
  server:
    container_name: mern-server
    build: ./server/
    restart: always
    ports:
      - "8081:8000"
    env_file:
      - ./environments/.env_server_prod
    volumes:
      - ./server/:/usr/src/app/
  gateway:
    container_name: gateway
    build: ./gateway/
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./gateway/:/usr/src/app/
  client:
    container_name: mern-client
    build: ./client/
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client/dist/:/usr/share/nginx/html/
