http:
  port: 8001
# admin:
#   port: 9876
#   host: localhost
apiEndpoints:
  api:
    methods: 'GET'
    host: localhost
    paths: '/ip'
  backend:
    methods: 'GET,PUT,POST,DELETE'
    host: localhost
    paths: '/api/v1/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  mernService:
    url: 'http://localhost:8000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  bin:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  mern:
    apiEndpoints:
      - backend
    policies:
      - proxy:
          - action:
              serviceEndpoint: mernService
              changeOrigin: true
